### ISSUE TITLE
doesn't work with a5100

### ISSUE THREAD

**Issue by buzmaxx** [jonasjuffinger/TimeLapse#14]

**Comment by jonasjuffinger** [comment]
Please post the log file TIMELPS/LOG.TXT.

Possible fixes: Set the drive mode to single or deactivate silent shutter

**Comment by petetum** [comment]
App installs succesfully on a5100 fw version v3.10
I can open app and change settings.
Once I hit START I get a black screen with the counter showing 0 then the camera reboots.
Does it every time regardless if silent shutter enabled or disabled.
