### ISSUE TITLE
Camera settings

### ISSUE THREAD

**Issue by terragady** [jonasjuffinger/TimeLapse#15]
Hi, it is very nice app and thank you for it! It works awesome on RX100m3
but I have to ask how are the camera settings used? White Balance and Focus, it seems that when I do not set a manual focus the camera tries to focus before the shot but sometimes it does not manage to do so but picture is still shot, same with WB, it stays the same all the time where for example ISO is changing with every pic when set to auto. Also on P mode the exposure is stable/permanent but should change from pic to pic with different light conditions etc?

**Comment by jonasjuffinger** [comment]
This is fixed with Version v1.1.0
