### ISSUE TITLE
I am using A7s and I have some questions 

### ISSUE THREAD

**Issue by JohnTa15** [jonasjuffinger/TimeLapse#25]
Hello,

What means AEL and BRC3 ? I searched it a lot and I couldn't found anything

Thanks for your time

**Comment by jonasjuffinger** [comment]
Hi,
I hadn't had time to update the Readme.

- AEL : Auto exposure lock. With this setting the camera locks the exposure after the first picture.
- BRC3: Bracket 3. With this setting the camera always takes three images for exposure bracketing. For this the Drive Mode must be set to Single Bracket 3 Image. It is just important that taking all three images doesn't take longer than the interval.

I hope that helps.

**Comment by JohnTa15** [comment]
Thanks for helping me
