### ISSUE TITLE
Display setting

### ISSUE THREAD

**Issue by hubuhubu** [jonasjuffinger/TimeLapse#33]
First off it's a great app, much more flexible than the sony app. Thanks a lot. 
I have a A6300 and I'm planning to take timelapse of the orchid flowers and it will be a long time lapse (3 weeks) so I don't want to leave the screen on for such a long time. 
There is a trick that force the display to only the viewfinder and the viewfinder will turn off if we don't look into it. This way the screen (both LCD and viewfinder) will turn off most of the time.
 
But it seems that your app would switch to the main display LCD after every shot regardless what configured in the camera. Is it possible to not forcing the camera to display on the LCD and only display on what configured by the camera ? 
Thanks,
Hung

**Comment by jonasjuffinger** [comment]
I removed the setting to turn off the display in one of the first versions, because it didn't have any impact on the battery life.
But that's of course another good reason to turn it off and I re-added this setting in the new version 1.4.
