### ISSUE TITLE
[Feature request] Adding 1/2 second interval. 

### ISSUE THREAD

**Issue by smensak** [jonasjuffinger/TimeLapse#40]
I recently found myself in situation where shortest (1s) interval was too long for my needs (shooting really fast moving clouds). Would you consider adding shorter interval(s) in future release (e.g. 0.5s)? Thank you.

**Comment by jonasjuffinger** [comment]
Hi smensak, I created the burst mode for that. In my tests I found that the a6300 cannot take pictures faster than in an 1s interval anyway when the buffer is full. In jpg mode you can shoot faster, but than you have only 8-bit pictures.
For faster intervals I usually shoot a video, with long exposure times.

**Comment by smensak** [comment]
Ah, I see. Thanks for clarification.
