### ISSUE TITLE
a6000 restarts after pressing 'start'

### ISSUE THREAD

**Issue by jakershill** [jonasjuffinger/TimeLapse#42]
regardless of settings in app, my a6000 turns off and restarts when pressing start, I have removed and reinstalled the app with no improvement. I have tried shooting both raw an jpeg.

camera is in manual mode.

**Comment by jonasjuffinger** [comment]
Hi, the app creates a log file on the SD Card in the TIMELPS folder. Can you please upload that one.

**Comment by jakershill** [comment]
Thanks for your help!

[LOG.TXT](https://github.com/jonasjuffinger/TimeLapse/files/5762319/LOG.TXT)

**Comment by jakershill** [comment]
Apologies, I have got this sorted, I think it may have been down to a poor quality battery.

**Comment by jonasjuffinger** [comment]
Great!
