### ISSUE TITLE
timesettings:  several steps between 1s and 5s

### ISSUE THREAD

**Issue by hubertmeier** [jonasjuffinger/TimeLapse#8]
This is a very usefull app, would it be possible to have some steps between 1s and 5s (1.5s, 2s, 3s, 5s). When writing RAW, 1s is too short ...

Thank you for your work

**Comment by jonasjuffinger** [comment]
These steps are selectable when you use one of the dials. What camera do you have?

**Comment by hubertmeier** [comment]
Oh, i didn't know that, i tested only the left-right buttons ... i will try it

I tested width NEX-6, A5100, and will test it with A7 series, RX1

Would it be possible to show something on the display between the frame capture like the number and / or the time of the remaining frames ?

**Comment by hubertmeier** [comment]
OK, i tested it

NEX-6: the slider works (1s, 5s ...), the wheels both do not work
A5100: the slider and the rotating keypad on the back work

**Comment by hubertmeier** [comment]
Oh, i did not want to close this issue ... sorry

**Comment by jonasjuffinger** [comment]
I just released a new version of the app, could you try it again?
